language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO=1.11.27
  - DJANGO=2.2.9
  - DJANGO=3.0.1

jobs:
  exclude:
    - python: 2.7
      env: DJANGO=2.2.9
    - python: 2.7
      env: DJANGO=3.0.1
    - python: 3.5
      env: DJANGO=1.11.27
    - python: 3.5
      env: DJANGO=3.0.1
    - python: 3.6
      env: DJANGO=1.11.27
    - python: 3.7
      env: DJANGO=1.11.27
    - python: 3.8
      env: DJANGO=1.11.27
    - python: 3.8
      env: DJANGO=2.2.9


install:
  - make install
  - pip install django==$DJANGO

script:
    make test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - ymy1019@gmail.com
